### ISSUE TITLE
Split MonkeyTypewriter into separate module

### ISSUE THREAD

**Issue by terinjokes** [brycebaril/infinite-monkey-db#1]
I find MonkeyTypewriter solves my problems, but I can't just require it. Can you please separate thus into another module?

By separating your modules into smaller modules, each one has a super small cone of concern. This makes writing tests super easy!

**Comment by brycebaril** [comment]
Just getting around to this (finally)... think MonkeyTypewriter would make a good Gulp module?

**Comment by terinjokes** [comment]
@brycebaril absolutely.
